# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Michael Seidel
  de: Michael Seidel
email: info@seidel-michael.de
description:
  en: I'm a software engineer.
  de: Ich bin ein Softwareentwickler.
index:
  en:
  de: index-de.html
feed:
  en: /feed.xml
  de: /feed-de.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.seidel-michael.de" # the base hostname & protocol for your site
github_username:  seidel-michael

# Build settings
markdown: kramdown
