# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
avatar: /images/avatar.jpg
name: Michael Seidel
jobtitle:
  en: Software Developer
  de: Softwareentwickler
title:
  en: Michael Seidel
  de: Michael Seidel
email: info@seidel-michael.de
description:
  en: Hello, I'm Michael, Software Developer and Scrum Master from Germany. My passion is to create high quality software that fits your needs.
  de: Hallo, mein Name ist Michael, ein Softwareentwickler und Scrum Master aus Deutschland. Meine Leidenschaft ist es, qualitativ hochwertige Software, die Ihren Bedürfnissen entspricht zu schaffen.
index:
  en:
  de: index-de.html
feed:
  en: /feed.xml
  de: /feed-de.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.seidel-michael.de" # the base hostname & protocol for your site
github_username:  seidel-michael
piwikurl: piwik.seidel-michael.de
piwikid: 1

# Build settings
markdown: kramdown
